config-version: 2
name: 'aws_cloud_cost'
version: '0.1.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  aws_cloud_cost:
    +schema: aws_cloud_cost
    +materialized: table
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: view
      +schema: stg_aws_cloud_cost


vars:
  cur: "{{ source('aws_cloud_cost', 'cur') }}"
