name: 'aws_cloud_cost_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  aws_cloud_cost:
    aws_cloud_cost_schema: aws_cloud_cost_integration_tests_3
    aws_cloud_cost_report_identifier: "aws_cost_report"