name: 'aws_cloud_cost_source_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  aws_cloud_cost_source:
    cost_report_identifier: "cost_report"
