name: 'aws_cloud_cost_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  aws_cloud_cost:
    # aws_cloud_cost_schema: aws_cloud_cost_integration_tests_3
    # aws_cloud_cost_report_identifier: "aws_cost_report"

    aws_cloud_cost_sources:
      - database: "{{ target.database }}"
        schema: aws_cloud_cost_integration_tests_3
        table: aws_cost_report 
        name: unique_name_for_source # not going to add has_defined_sources for now

models:
  +schema: "aws_cloud_cost_{{ var('directed_schema','dev') }}"

seeds:
  aws_cloud_cost_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    aws_cost_report:
      +column_types:
        line_item_usage_start_date: timestamp
        line_item_usage_end_date: timestamp
        bill_billing_period_start_date: timestamp
        bill_billing_period_end_date: timestamp
        bill_bill_type: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"